sudo: false
language: cpp
addons:
  apt:
    packages:
    - g++-multilib
compiler:
  - clang
before_script:
  - CHECKOUT_DIR=$PWD && cd .. && git clone --recursive https://github.com/alliedmodders/sourcemod && git clone https://github.com/alliedmodders/ambuild && cd ambuild && python setup.py install --user && cd $CHECKOUT_DIR
script:
  - mkdir build && cd build
  - python ../configure.py --enable-optimize
  - ~/.local/bin/ambuild
